version: '3'

services:
  app:
    build: .
    container_name: app
    volumes: 
      - .:/var/www

  server:
    build: .docker/nginx
    container_name: server
    restart: always
    tty: true
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
  
  database:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: database
    restart: always
    tty: true
    ports:
      - "33006:3306"
    volumes:
      - ./.docker/database_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
  redis:
    image: redis:alpine
    expose:
      - "6379"
